# Site settings
name: "studio franklin"
description: ""
url: "http://rosannevdw.github.io"
githubUsername: rosannevdw

# Build settings
permalink: pretty

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""  # empty string for all files
      type: projects
    values:
      layout: default
      is_post: true
